### ISSUE TITLE
Type incorrect in user data alteration example?

### ISSUE THREAD

**Issue by Skarlso** [mikestefanello/hooks#1]
Hello! 

Neat project. While I was reading, I noticed this example:

```go
HookUserPreInsert.Listen(func(e hooks.Event[user.User]) {
    // Change the user's name
    e.Msg.Name = fmt.Sprintf("%s-changed", e.Msg.Name)
})
```

Shouldn't this be of type `hooks.Event[*user.User]`? Since your other PreInsert is using `*User`.

But I might be wrong. :)

**Comment by mikestefanello** [comment]
Yes! Thanks. I'll update now.
