### ISSUE TITLE
nil check in logf vs surrounding the call.

### ISSUE THREAD

**Issue by WillRubin** [mikestefanello/hooks#3]
Minor issue but having the nil check in the logf function means every call has to setup a call stack, evaluate parameters, and perform the call even if logger is nil. This is most noticeable in the dispatch function, which might be called repeatedly in a tighter loop. Would moving the nil test outside logf to surround the calls be appropriate?
```
ex:
if logger != nil {
  logf("dispatching hook %s to %d listeners (async: %v)", h.GetName(), len(h.listeners), async)
} 
```

**Comment by mikestefanello** [comment]
Understandable point. 

We could set the `logger` to something like an empty _func_ by default, so it's never `nil`, and thus we just accept that the logger will be always executed.

IE:

```go
func init() {
    SetLogger(func(format string, args ...any) {})
}
```

It doesn't _solve_ the issue though, obviously, but it eliminates it in a way.

The problem with doing the `nil` check for all calls is that you not only get some code bloat, but my main concern is that one has to know to always do the check prior to calling; which is really error-prone. Sure, tests can try to catch this, but it feels off to me.

Thoughts?

**Comment by WillRubin** [comment]
I think nil is fine. Maybe even more Go-like. Leaving it in the logger is fine too. In practice, wrapping just the dispatch call would be enough. The other places are called much less frequently and in non-critical locations.

Maybe a comment for explanation to others and yourself later on.
```
if logger != nil { // for speed and efficiency
```

**Comment by mikestefanello** [comment]
Okay, I see what you're saying - keep the check where it is, but add it in the place that will be called often. Good idea.

Thanks for the suggestion: https://github.com/mikestefanello/hooks/commit/d596279a56262dd729996c8584d201c23b839f53

**Comment by mikestefanello** [comment]
For reference, I did some benchmarking just to see the difference and dispatching (with 3 listeners) went from 212.4 ns/op to 70.59 ns/op.
